import type {InfoContent} from "./info-types";

// Original suggested itineraries; linked primary sources support venue details.
// The events coverage report informed city selection, not live event availability.
export const cityBreakGuides:Record<string,InfoContent>={
 "milan-weekend":{
  title:"Mediolan na weekend: co zobaczyć w 2 dni",
  description:"Plan dwóch dni w Mediolanie: Duomo, Brera i Navigli. Co zarezerwować, jak ułożyć spacery i gdzie zmieścić koncert.",
  draft:false,reviewedAt:"2026-10-02",category:"destinations",
  paragraphs:["Na pierwszy weekend w Mediolanie proponujemy centrum i Brerę pierwszego dnia, a okolice zamku oraz Navigli drugiego. To autorski plan na dwa pełne dni na miejscu. Jeśli przylatujesz w sobotę po południu, wybierz jeden spacer i jedną główną atrakcję zamiast próbować odrobić cały poranek."],
  sections:[
   {title:"Dzień 1: Duomo, galeria i Brera",paragraphs:["Zacznij od Piazza del Duomo, przejdź przez Galleria Vittorio Emanuele II i okolice La Scali, a następnie skieruj się do Brery. Ten układ pozwala połączyć reprezentacyjne centrum z przerwą na obiad i spokojniejszym spacerem. Duomo, Brera i Navigli pojawiają się również w trasie oficjalnego portalu YesMilano.","Jeśli chcesz wejść do katedry lub na tarasy, potraktuj wybraną godzinę jako punkt stały dnia. Nie dopisuj od razu kolejnego muzeum: zostaw czas na kolejkę, kontrolę wejścia i posiłek. Przy samym spacerze po centrum możesz zachować znacznie większą swobodę."],sourceIds:[0]},
   {title:"Tarasy Duomo: wybierz właściwy zakres biletu",paragraphs:["Tarasy są osobnym doświadczeniem od oglądania fasady z placu. Oficjalna strona opisuje kolejne poziomy i schody prowadzące na taras centralny. Przed zakupem sprawdź wariant wejścia i aktualne informacje o dostępności; sama opcja windy nie wystarcza do oceny całej trasy dla osoby z ograniczoną mobilnością."],sourceIds:[1]},
   {title:"Dzień 2: zamek, park i wieczór nad kanałami",paragraphs:["Zaplanuj poranek przy Castello Sforzesco i spacer w stronę Parco Sempione. Po południu przenieś się w okolice Darseny i Navigli. To propozycja dwóch bloków, między którymi możesz odpocząć w hotelu, a nie obowiązek przejścia całej trasy pieszo.","Jeżeli wieczorem masz koncert, skróć drugą część. Wpisz w mapę dokładny adres sali i sprawdź powrót do noclegu po wydarzeniu. Nazwa „Milano” przy wydarzeniu nie oznacza, że sala leży przy Duomo lub kanałach."],sourceIds:[0]},
   {title:"Deszcz i krótki pobyt: co wykreślić",paragraphs:["Na deszczowy dzień wybierz jedną wizytę we wnętrzu, która naprawdę cię interesuje, i skróć spacery. Godzinę zwiedzania sprawdź przed zakupem, a kawiarnię potraktuj jako przerwę w trasie. Przy wylocie tego samego wieczoru zrezygnuj z najdalszego punktu zamiast zmniejszać zapas na transfer.","Przed wyborem noclegu porównaj drogę z właściwego lotniska: Linate, Malpensa i Bergamo wymagają różnych planów. Najpierw policz czas od lądowania do pozostawienia bagażu, dopiero potem wybierz pierwszy bilet wstępu."]},
  ],sources:[
   {label:"YesMilano — trasa na dwa dni",href:"https://www.yesmilano.it/en/see-and-do/itineraries/two-days-milano"},
   {label:"Duomo di Milano — tarasy i ich układ",href:"https://www.duomomilano.it/en/art-and-culture/the-terraces/"},
  ],routes:[{label:"Sprawdź aktualne loty",href:"/deals"}],related:["milan-airports","concert-trip","city-break-planning"],
 },
 "paris-weekend":{
  title:"Paryż na weekend: plan zwiedzania na 2 dni",
  description:"Pierwszy weekend w Paryżu: spacer nad Sekwaną, Luwr lub Montmartre. Plan z miejscem na rezerwacje, odpoczynek i transfer.",
  draft:false,reviewedAt:"2026-10-02",category:"destinations",
  paragraphs:["Dwa dni w Paryżu warto oprzeć na dwóch obszarach i jednej dużej atrakcji dziennie. Proponujemy pierwszy dzień nad Sekwaną, a drugi na Montmartre. Jeśli głównym celem jest Luwr, przeznacz na niego osobny blok i skróć resztę programu. Poniższa kolejność jest propozycją redakcji, którą należy dopasować do godzin wejścia i lotów."],
  sections:[
   {title:"Dzień 1: Sekwana i okolice Luwru",paragraphs:["Zacznij w okolicy Île de la Cité, następnie przejdź wzdłuż Sekwany w stronę Luwru i ogrodu Tuileries. Zaplanuj przerwę na jedzenie przed kolejnym etapem. Oglądanie budynków z zewnątrz i wejście do muzeum to dwa różne warianty dnia: nie licz ich jako jednego krótkiego przystanku.","Wieżę Eiffla możesz wybrać zamiast rozbudowanego zwiedzania muzeum. Jeśli zależy ci na wjeździe, najpierw sprawdź dostępny termin u operatora, a następnie ułóż dojazd. Nie obiecujemy połączenia wszystkich tych miejsc w jednym spokojnym spacerze."]},
   {title:"Luwr: dzień tygodnia zmienia kolejność",paragraphs:["Luwr podaje wtorek jako dzień zamknięcia. Na oficjalnej stronie sprawdzisz również godziny, wyjątki i rezerwację wejścia. Jeśli twój „weekend” wypada w poniedziałek i wtorek, nie zostawiaj muzeum automatycznie na drugi dzień.","Wybierz wcześniej interesującą cię część kolekcji. Zapisz wejście wskazane na rezerwacji, zostaw czas na kontrolę i nie rezerwuj kolejnej atrakcji bezpośrednio po planowanym wyjściu. Cenę oraz ewentualne uprawnienia do ulg potwierdź w oficjalnej sprzedaży dla uczestników wyjazdu."],sourceIds:[0]},
   {title:"Dzień 2: Montmartre we własnym tempie",paragraphs:["Drugi poranek przeznacz na okolice Abbesses, Place du Tertre i Sacré-Cœur. Oficjalny portal turystyczny proponuje spacer po Montmartre i wskazuje także kolejkę przy rue Foyatier. Wybierz dojście z uwzględnieniem nachylenia terenu i własnych możliwości.","Po spacerze zaplanuj obiad i jeden opcjonalny punkt. Przy wieczornym koncercie zostaw resztę popołudnia na przejazd i odpoczynek; przy odlocie wróć po bagaż. Nie dodawaj Wersalu tylko dlatego, że na mapie znajduje się w regionie paryskim — potrzebowałby osobnego planu."],sourceIds:[1]},
   {title:"Nocleg i wariant na deszcz",paragraphs:["Porównaj noclegi przez czas dojazdu do swoich dwóch głównych punktów, a nie samą odległość od środka mapy. Sprawdź przesiadki z bagażem i możliwość późnego zameldowania. Dla Beauvais zaplanuj transfer oddzielnie od transportu z CDG lub Orly.","Na deszcz zamień długi spacer na wybrane muzeum, jeśli jest otwarte i ma dostępne wejścia. Rezerwacja muzeum jako wariantu awaryjnego ma sens tylko wtedy, gdy akceptujesz jej warunki. Nie traktuj pogody jako gwarancji dostępności biletów tego samego dnia."]},
  ],sources:[
   {label:"Musée du Louvre — godziny i rezerwacje",href:"https://www.louvre.fr/en/visit/hours-admission"},
   {label:"Paris je t’aime — spacer po Montmartre",href:"https://parisjetaime.com/eng/article/village-paris-a922"},
  ],routes:[{label:"Sprawdź aktualne loty",href:"/deals"}],related:["paris-airports","city-break-planning","concert-trip"],
 },
 "stockholm-weekend":{
  title:"Sztokholm w 2 dni: Gamla Stan i Djurgården",
  description:"Weekend w Sztokholmie: stare miasto, muzea na Djurgården, plan na deszcz oraz wybór noclegu i transferu z lotniska.",
  draft:false,reviewedAt:"2026-10-02",category:"destinations",
  paragraphs:["Na pierwszy pobyt w Sztokholmie proponujemy dzień w Gamla Stan i dzień na Djurgården. Dzięki temu nie trzeba wielokrotnie przemieszczać się między odległymi punktami. Plan zakłada dwa pełne dni; przy późnym przylocie zacznij od kolacji i krótkiego spaceru, a muzeum zostaw na następny poranek."],
  sections:[
   {title:"Dzień 1: Gamla Stan bez pośpiechu",paragraphs:["Gamla Stan to historyczna dzielnica Sztokholmu. Zacznij od Stortorget, przejdź uliczkami w stronę pałacu królewskiego i zrób przerwę przed kolejnym spacerem. Oficjalny portal miasta opisuje w tej części m.in. pałac oraz Nobel Prize Museum; wybierz jedno wnętrze, jeśli chcesz uzupełnić spacer zwiedzaniem.","Nie buduj całego planu wokół ceremonii, której godziny nie sprawdzono. Lepiej potraktować potwierdzone wydarzenie jako punkt dodatkowy. Popołudnie zostaw na nabrzeże lub odpoczynek, szczególnie jeśli wieczorem wybierasz się do teatru."],sourceIds:[0]},
   {title:"Dzień 2: jedno główne muzeum na Djurgården",paragraphs:["Visit Stockholm wymienia na Djurgården m.in. muzeum Vasa, Skansen i ABBA The Museum. Wybierz atrakcję według zainteresowań grupy: kilka dużych obiektów jednego dnia łatwo zamienia się w wyścig. Po głównej wizycie zostaw czas na posiłek i spacer zamiast kupować od razu trzy bilety.","Przed wyjściem porównaj drogę pieszą i aktualne połączenia transportem miejskim z noclegu. Jeżeli wybierasz statek, sprawdź konkretną linię i zakres biletu — rejs turystyczny i transport publiczny mogą być różnymi usługami."],sourceIds:[1]},
   {title:"Vasa jako plan na gorszą pogodę",paragraphs:["Oficjalna strona Vasa publikuje godziny otwarcia, informacje o biletach i dojeździe. Sprawdź je dla swojego dnia, zanim przeniesiesz muzeum z drugiego poranka na pierwszy. Zaplanuj czas również na pozostawienie rzeczy zgodnie z zasadami obiektu.","Jeśli prognoza jest niepewna, zachowaj możliwość zamiany dni. Nie rezerwuj dwóch atrakcji na przeciwległych końcach miasta w sąsiednich godzinach. Wieczorny koncert może pozostać stałym punktem, a spacery da się skrócić."],sourceIds:[2]},
   {title:"Budżet weekendu i wybór lotniska",paragraphs:["Zestaw koszty dwóch noclegów, transportu z lotniska w obie strony, wybranych muzeów i posiłków. Każdy wydatek zapisuj w jego walucie, a do porównania wariantów zastosuj jeden jawny sposób przeliczenia. Sama cena lotu nie opisuje budżetu pobytu.","Arlanda i Skavsta wymagają różnych transferów. Przed zakupem lotu policz, ile czasu zostanie od zameldowania do zamknięcia wybranego muzeum. Przy porannym powrocie sprawdź pierwszy możliwy transport do konkretnego portu, a nie tylko do centrum Sztokholmu."]},
  ],sources:[
   {label:"Visit Stockholm — Gamla Stan",href:"https://www.visitstockholm.com/stockholms-districts/gamla-stan/"},
   {label:"Visit Stockholm — atrakcje Djurgården",href:"https://www.visitstockholm.com/see-do/attractions/district-guide-djurgarden/"},
   {label:"Vasamuseet — zaplanuj wizytę",href:"https://www.vasamuseet.se/en/visit"},
  ],routes:[{label:"Sprawdź aktualne loty",href:"/deals"}],related:["stockholm-airports","oslo-weekend","concert-trip"],
 },
 "oslo-weekend":{
  title:"Oslo na weekend: fiord, opera i muzea w 2 dni",
  description:"Co zobaczyć w Oslo przez dwa dni: nabrzeże, okolice opery i MUNCH. Elastyczny plan spacerów, muzeum i wieczornego wydarzenia.",
  draft:false,reviewedAt:"2026-10-02",category:"destinations",
  paragraphs:["Weekend w Oslo proponujemy podzielić na spacer przy fiordzie i dzień z jednym głównym muzeum. Nie trzeba przechodzić całego nabrzeża ani kupować biletu do każdej atrakcji. Plan jest propozycją na dwa pełne dni; długość spacerów dostosuj do pogody i godzin powrotu."],
  sections:[
   {title:"Dzień 1: okolice opery i Bjørvika",paragraphs:["Zacznij przy operze i przejdź nabrzeżem w okolicy Bjørvika. VisitOSLO opisuje promenadę portową jako trasę łączącą architekturę, kulturę i miejsca odpoczynku. Wybierz fragment, który pasuje do twojej kondycji i czasu, zamiast traktować całą promenadę jako obowiązkową trasę.","Spacer przy operze i bilet na spektakl to odrębne plany. Jeśli chcesz zobaczyć przedstawienie, sprawdź repertuar, godzinę i dostępność osobno. Przy wietrze lub deszczu skróć część nad wodą, zachowując przerwę na obiad."],sourceIds:[0]},
   {title:"Dzień 2: MUNCH i spokojniejsze popołudnie",paragraphs:["Jako główny punkt drugiego dnia proponujemy MUNCH. Oficjalna strona muzeum zawiera informacje o wizycie i aktualnym programie. Najpierw wybierz interesującą wystawę i godzinę, dopiero potem dobierz resztę dnia. Nie zakładaj, że każdy znany obraz będzie dostępny w dowolnym momencie.","Po muzeum zostaw popołudnie na dalszy spacer, posiłek lub powrót po bagaż. Jeżeli masz wieczorne wydarzenie, sprawdź jego adres: muzeum, sala koncertowa i hotel mogą wymagać osobnych przejazdów."],sourceIds:[1]},
   {title:"Drugi spacer: Aker Brygge i Tjuvholmen",paragraphs:["Aker Brygge i Tjuvholmen to kolejny fragment nabrzeża opisany przez VisitOSLO. Możesz wybrać tę część zamiast długiego spaceru w Bjørvika albo zostawić ją na popołudnie. Trasa jest propozycją oglądania miasta; wejścia do muzeów po drodze planuj i wyceniaj osobno.","Zanim dołożysz rejs po fiordzie, sprawdź trasę, port wypłynięcia, powrót i sezon działania. Nie traktuj samego słowa „fiord” jako jednego produktu. Przy krótkim pobycie spacer nad wodą może wystarczyć, aby nie podporządkować całego dnia kolejnemu rozkładowi."],sourceIds:[0]},
   {title:"Gdzie szukać oszczędności w planie",paragraphs:["Porównaj nocleg z dojazdem do głównych punktów, nie tylko cenę pokoju. Ułóż listę płatnych atrakcji, które rzeczywiście odwiedzisz. Kartę miejską oceniaj na podstawie jej aktualnego zakresu i tej listy, a nie liczby wszystkich reklamowanych muzeów.","Przed rezerwacją lotu zapisz kod lotniska i sprawdź pełny dojazd do noclegu. Na dzień powrotu zostaw lekki program bez kolejnych biletów na sztywną godzinę. Koszt przejazdu po koncercie dopisz do budżetu, jeśli rozkład nie pozwala wrócić wybranym transportem."]},
  ],sources:[
   {label:"VisitOSLO — promenada portowa",href:"https://www.visitoslo.com/articles/the-harbour-promenade"},
   {label:"MUNCH — informacje dla odwiedzających",href:"https://www.munch.no/en/visit-us/"},
  ],routes:[{label:"Sprawdź aktualne loty",href:"/deals"}],related:["stockholm-weekend","city-break-planning","concert-trip"],
 },
 "concert-trip":{
  title:"Wyjazd na koncert za granicę: lot, nocleg i bilety",
  description:"Jak zaplanować podróż na koncert: zgodność dat, dojazd do sali, bilet mobilny, powrót po występie i budżet całego wyjazdu.",
  draft:false,reviewedAt:"2026-10-02",category:"planning",
  paragraphs:["Podróż na koncert zacznij od konkretnego wydarzenia: daty, sali i możliwości zakupu właściwego biletu. Dopiero z tymi informacjami porównuj loty i noclegi. Tani przylot w dniu występu ma niewielką wartość, jeśli po transferze zabraknie czasu na wejście. Poniżej proponujemy kolejność planowania dla samodzielnie organizowanego wyjazdu."],
  sections:[
   {title:"Najpierw zapisz komplet danych wydarzenia",paragraphs:["W jednej notatce umieść artystę, datę lokalną, pełny adres sali, otwarcie drzwi i początek występu, jeśli podano je osobno. Sprawdź oficjalną stronę organizatora oraz sprzedawcę wskazanego przez niego. Nazwa trasy koncertowej bez miasta i daty nie wystarcza do zakupu lotu.","Sprawdź kategorię biletu, ograniczenia wiekowe i zasady wejścia z torbą na stronie konkretnego obiektu. Nie przenoś zasad z innej sali. Jeżeli masz tylko listę wydarzeń dla danego miasta, potraktuj ją jako początek poszukiwań, a nie potwierdzenie, że zdążysz po lądowaniu."]},
   {title:"Rozpisz dzień od drzwi sali wstecz",paragraphs:["Od planowanej godziny wejścia odejmij czas dojazdu z hotelu, pozostawienia bagażu, transferu z lotniska i wyjścia z terminala. Dodaj osobny zapas na zakłócenia. Gdy plan działa tylko przy punktualnym przylocie i natychmiastowym transferze, rozważ przylot dzień wcześniej.","Przykład organizacyjny, nie rozkład: dla występu o 20:00 i lądowania o 17:30 pozostaje 2,5 godziny na wszystkie etapy, nie na sam przejazd. Bez znajomości lotniska, sali i transportu nie można uznać takiego wariantu za wykonalny."]},
   {title:"Bilet mobilny sprawdź przed wyjazdem",paragraphs:["Ticketmaster UK wyjaśnia, że bilety z ruchomym kodem wymagają aktualnego kodu i zrzut ekranu nie umożliwia wejścia. To przykład konkretnego systemu, nie zasada każdego sprzedawcy. Sprawdź sposób prezentacji dokładnie swojego biletu.","Zaloguj się do właściwego konta, upewnij się, że widzisz rezerwację, i przygotuj wymagany sposób dostępu. Instrukcja Ticketmaster opisuje aplikację i portfel mobilny; dostępność danej opcji sprawdź dla wydarzenia. Naładuj telefon i ustal, kto przechowuje bilety grupy."],sourceIds:[0,1]},
   {title:"Powrót po koncercie i rzeczy w hotelu",paragraphs:["Sprawdź ostatnie połączenia spod sali do noclegu na konkretny dzień. Nie zakładaj, że wydarzenie skończy się o wybranej przez ciebie godzinie. Jeżeli potrzebujesz innego transportu, uwzględnij go w kosztach przed kupnem biletów.","Zapytaj nocleg o możliwość pozostawienia bagażu i godziny zameldowania. Duży plecak podróżny może wymagać innego planu niż mała torba na wieczór; sprawdź regulamin sali i dostępność przechowalni zamiast zakładać, że przy wejściu będzie szatnia."]},
   {title:"Policz wszystkie rezerwacje razem",paragraphs:["Zsumuj loty, bagaż, noclegi, bilety na wydarzenie i przejazdy dla tej samej liczby osób. Przed każdą płatnością sprawdź ponownie dostępność pozostałych elementów oraz warunki zmian. Osobno kupowane usługi wymagają osobnego sprawdzenia ich zasad.","Na zwiedzanie wybierz program, który łatwo skrócić: spacer po Brerze, Gamla Stan lub nabrzeżu Oslo. Dzień koncertu zostaw z mniejszą liczbą rezerwacji na konkretną godzinę. Przykładowe trasy znajdziesz w powiązanych poradnikach."]},
  ],sources:[
   {label:"Ticketmaster UK — bilety z ruchomym kodem",href:"https://help.ticketmaster.co.uk/hc/en-us/articles/13756245361297-Why-do-my-tickets-have-a-moving-barcode"},
   {label:"Ticketmaster UK — bilety mobilne",href:"https://www.ticketmaster.co.uk/mobile-tickets"},
  ],routes:[{label:"Porównaj loty na swój termin",href:"/deals"}],related:["milan-weekend","paris-weekend","stockholm-weekend","oslo-weekend","trip-budget"],
 },
 "city-break-planning":{
  title:"Jak zaplanować city break na 2–3 dni",
  description:"Krótki wyjazd krok po kroku: policz czas na miejscu, wybierz nocleg, ułóż trasę i zdecyduj, które atrakcje rezerwować wcześniej.",
  draft:false,reviewedAt:"2026-10-02",category:"planning",
  paragraphs:["City break zacznij od policzenia czasu, który rzeczywiście spędzisz w mieście. Dwie noce mogą oznaczać dwa pełne dni albo tylko jeden dzień między późnym przylotem i wczesnym odlotem. Poniższy schemat pomaga porównać te warianty i ułożyć program bez kupowania biletów na każdą wolną godzinę."],
  sections:[
   {title:"Krok 1: policz użyteczne godziny",paragraphs:["Zapisz przewidywaną godzinę dotarcia do noclegu oraz godzinę, o której trzeba wyruszyć na lotnisko w drodze powrotnej. Pomiędzy nimi zaznacz sen, posiłki i obowiązkowe przejazdy. Dopiero pozostały czas przeznacz na zwiedzanie.","Przykład obliczeniowy: przy dotarciu w piątek o 22:00 i wyjeździe na lotnisko w niedzielę o 06:00 masz głównie sobotę na miasto. Droższy lot powrotny po południu może dać dodatkowy poranek, ale wymaga porównania pełnej różnicy kosztów. Podane godziny nie opisują oferty lotniczej."]},
   {title:"Krok 2: wybierz jeden główny cel dziennie",paragraphs:["Wypisz trzy rzeczy, dla których chcesz jechać: na przykład muzeum, dzielnicę i koncert. Oznacz, które mają sztywną godzinę. Rozmieść je w planie, a pozostałe punkty traktuj jako opcjonalne. Trasa powinna umożliwiać opuszczenie jednego przystanku bez utraty kolejnych rezerwacji.","Sprawdź dzień tygodnia. Przykładowo Luwr podaje wtorek jako dzień zamknięcia; popularność atrakcji nie oznacza dostępności każdego dnia. Przed zakupem korzystaj z kalendarza konkretnego obiektu, uwzględniając wyjątki i termin podróży."],sourceIds:[0]},
   {title:"Krok 3: wybierz nocleg razem z trasą",paragraphs:["Dla dwóch lub trzech noclegów porównaj całkowitą kwotę za pobyt, warunki zameldowania i dojazd do wybranych atrakcji. Tani pokój daleko od trasy może wymagać dodatkowych biletów i powtarzanych przejazdów. Zapisz czas od przystanku do wejścia z bagażem.","Jeśli ostatni dzień zaczyna się od wymeldowania, ustal wcześniej przechowanie rzeczy. Nie kupuj wejścia do muzeum bez czasu na odbiór bagażu przed transferem na lotnisko. Przy podróży w kilka osób sprawdź, czy wszyscy akceptują tempo i długość spacerów."]},
   {title:"Krok 4: przygotuj wersję krótszą i deszczową",paragraphs:["Dla każdego dnia zapisz punkt obowiązkowy, punkt opcjonalny i miejsce na przerwę. Na deszcz wybierz jedno wnętrze, ale sprawdź aktualne wejścia; na opóźniony przylot przygotuj krótszy spacer. Dzięki temu zmiana pogody nie wymaga układania całego wyjazdu od początku.","Dobrym sposobem grupowania atrakcji jest jedna dzielnica na część dnia. Oficjalny przewodnik po Djurgården pokazuje skupienie muzeów i miejsc spacerowych w jednym obszarze Sztokholmu. Wybierz spośród nich własny zestaw zamiast traktować całą listę jako plan do wykonania."],sourceIds:[1]},
   {title:"Krok 5: ostatnia kontrola przed płatnością",paragraphs:["Sprawdź daty i kody lotnisk, zakres bagażu, liczbę nocy, cenę całej rezerwacji noclegu, godziny atrakcji oraz transport powrotny. Brakującą cenę oznacz jako do sprawdzenia. Do budżetu wpisuj tylko znane koszty, oddzielając je od własnej rezerwy na wydatki.","Po zakupie zbierz potwierdzenia, adres noclegu, instrukcje wejścia i rozkład transferu w jednym miejscu dostępnym podczas podróży. Przed wyjazdem ponownie sprawdź komunikaty operatorów. Gotowe propozycje weekendów znajdziesz poniżej."]},
  ],sources:[
   {label:"Musée du Louvre — dni i godziny otwarcia",href:"https://www.louvre.fr/en/visit/hours-admission"},
   {label:"Visit Stockholm — muzea i spacery na Djurgården",href:"https://www.visitstockholm.com/see-do/attractions/district-guide-djurgarden/"},
  ],routes:[{label:"Znajdź lot na krótki wyjazd",href:"/deals"}],related:["milan-weekend","paris-weekend","stockholm-weekend","oslo-weekend","trip-budget","baggage"],
 },
};
